#require_relative 'utah_county_aa_meeting_finder/version'
require_relative '../lib/utah_county_aa_meeting_finder/cli'
require_relative '../lib/utah_county_aa_meeting_finder/version'
require_relative '../lib/utah_county_aa_meeting_finder/meetings'
require_relative '../lib/utah_county_aa_meeting_finder/scraper'
require 'pry'
require 'nokogiri'
require 'open-uri'
